export const category = [
    { value: 'Make friends', icon: 'group-work', code: 0 }, 
    { value: 'Fun & Random', icon: 'shuffle', code: 1 }, 
    { value: 'Arts & Design', icon: 'palette', code: 2 }, 
    { value: 'Arts & Culture', icon: 'groups', code: 3 }, 
    { value: 'Automotive', icon: 'directions-car', code: 4 }, 
    { value: 'Books', icon: 'menu-book', code: 5 }, 
    { value: 'Business & Finance', icon: 'attach-money', code: 6 }, 
    { value: 'Developers', icon: 'code', code: 7 }, 
    { value: 'Fashion & Beauty', icon: 'checkroom', code: 8 }, 
    { value: 'Food & Drink', icon: 'fastfood', code: 9 }, 
    { value: 'Health & Fitness', icon: 'fitness-center', code: 10 }, 
    { value: 'Hobbies & Leisure', icon: 'sports-tennis', code: 11 }, 
    { value: 'Home & Garden', icon: 'home', code: 12 }, 
    { value: 'Movies', icon: 'movie', code: 13 }, 
    { value: 'Music', icon: 'music-note', code: 14 }, 
    { value: 'Parenting', icon: 'supervisor-account', code: 15 }, 
    { value: 'Personal Development', icon: 'self-improvement', code: 16 }, 
    { value: 'Science & Nature', icon: 'science', code: 17 }, 
    { value: 'Sports & Athletics', icon: 'sports-football', code: 18 }, 
    { value: 'Technology', icon: 'biotech', code: 19 }, 
    { value: 'Travel', icon: 'map', code: 20 }, 
    { value: 'Gaming', icon: 'sports-esports', code: 21 }, 
    { value: 'Entertainment', icon: 'casino', code: 22 }, 
];